// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: shipment.proto

package shipment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShipmentStatus defines the lifecycle states of a shipment
type ShipmentStatus int32

const (
	ShipmentStatus_STATUS_UNSPECIFIED ShipmentStatus = 0
	ShipmentStatus_STATUS_PENDING     ShipmentStatus = 1 // Initial status - shipment created
	ShipmentStatus_STATUS_PICKED_UP   ShipmentStatus = 2 // Driver picked up the shipment
	ShipmentStatus_STATUS_IN_TRANSIT  ShipmentStatus = 3 // Shipment is on the way
	ShipmentStatus_STATUS_DELIVERED   ShipmentStatus = 4 // Shipment successfully delivered
	ShipmentStatus_STATUS_CANCELLED   ShipmentStatus = 5 // Shipment cancelled
	ShipmentStatus_STATUS_FAILED      ShipmentStatus = 6 // Delivery failed
)

// Enum value maps for ShipmentStatus.
var (
	ShipmentStatus_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PENDING",
		2: "STATUS_PICKED_UP",
		3: "STATUS_IN_TRANSIT",
		4: "STATUS_DELIVERED",
		5: "STATUS_CANCELLED",
		6: "STATUS_FAILED",
	}
	ShipmentStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_PENDING":     1,
		"STATUS_PICKED_UP":   2,
		"STATUS_IN_TRANSIT":  3,
		"STATUS_DELIVERED":   4,
		"STATUS_CANCELLED":   5,
		"STATUS_FAILED":      6,
	}
)

func (x ShipmentStatus) Enum() *ShipmentStatus {
	p := new(ShipmentStatus)
	*p = x
	return p
}

func (x ShipmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShipmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shipment_proto_enumTypes[0].Descriptor()
}

func (ShipmentStatus) Type() protoreflect.EnumType {
	return &file_shipment_proto_enumTypes[0]
}

func (x ShipmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShipmentStatus.Descriptor instead.
func (ShipmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{0}
}

// Shipment represents the main shipment entity
type Shipment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                          // Unique identifier (UUID)
	ReferenceNumber string                 `protobuf:"bytes,2,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`                         // Human-readable reference
	Origin          string                 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`                                                                  // Origin address
	Destination     string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`                                                        // Destination address
	CurrentStatus   ShipmentStatus         `protobuf:"varint,5,opt,name=current_status,json=currentStatus,proto3,enum=shipment.ShipmentStatus" json:"current_status,omitempty"` // Current shipment status
	Driver          *DriverDetails         `protobuf:"bytes,6,opt,name=driver,proto3" json:"driver,omitempty"`                                                                  // Driver information
	Unit            *UnitDetails           `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`                                                                      // Vehicle/unit information
	ShipmentAmount  float64                `protobuf:"fixed64,8,opt,name=shipment_amount,json=shipmentAmount,proto3" json:"shipment_amount,omitempty"`                          // Total shipment cost
	DriverRevenue   float64                `protobuf:"fixed64,9,opt,name=driver_revenue,json=driverRevenue,proto3" json:"driver_revenue,omitempty"`                             // Driver's revenue
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                          // Creation timestamp
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                          // Last update timestamp
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_shipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{0}
}

func (x *Shipment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shipment) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *Shipment) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Shipment) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Shipment) GetCurrentStatus() ShipmentStatus {
	if x != nil {
		return x.CurrentStatus
	}
	return ShipmentStatus_STATUS_UNSPECIFIED
}

func (x *Shipment) GetDriver() *DriverDetails {
	if x != nil {
		return x.Driver
	}
	return nil
}

func (x *Shipment) GetUnit() *UnitDetails {
	if x != nil {
		return x.Unit
	}
	return nil
}

func (x *Shipment) GetShipmentAmount() float64 {
	if x != nil {
		return x.ShipmentAmount
	}
	return 0
}

func (x *Shipment) GetDriverRevenue() float64 {
	if x != nil {
		return x.DriverRevenue
	}
	return 0
}

func (x *Shipment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Shipment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// DriverDetails contains driver information
type DriverDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`          // Driver unique identifier
	DriverName    string                 `protobuf:"bytes,2,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`    // Driver full name
	DriverPhone   string                 `protobuf:"bytes,3,opt,name=driver_phone,json=driverPhone,proto3" json:"driver_phone,omitempty"` // Driver contact number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverDetails) Reset() {
	*x = DriverDetails{}
	mi := &file_shipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverDetails) ProtoMessage() {}

func (x *DriverDetails) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverDetails.ProtoReflect.Descriptor instead.
func (*DriverDetails) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{1}
}

func (x *DriverDetails) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverDetails) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *DriverDetails) GetDriverPhone() string {
	if x != nil {
		return x.DriverPhone
	}
	return ""
}

// UnitDetails contains vehicle/unit information
type UnitDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        string                 `protobuf:"bytes,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`                // Vehicle/unit unique identifier
	UnitType      string                 `protobuf:"bytes,2,opt,name=unit_type,json=unitType,proto3" json:"unit_type,omitempty"`          // Type of vehicle (truck, van, etc.)
	PlateNumber   string                 `protobuf:"bytes,3,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"` // Vehicle license plate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitDetails) Reset() {
	*x = UnitDetails{}
	mi := &file_shipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitDetails) ProtoMessage() {}

func (x *UnitDetails) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitDetails.ProtoReflect.Descriptor instead.
func (*UnitDetails) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{2}
}

func (x *UnitDetails) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *UnitDetails) GetUnitType() string {
	if x != nil {
		return x.UnitType
	}
	return ""
}

func (x *UnitDetails) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

// StatusEvent represents a shipment status change event
type StatusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                       // Event unique identifier
	ShipmentId    string                 `protobuf:"bytes,2,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`     // Reference to shipment
	Status        ShipmentStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=shipment.ShipmentStatus" json:"status,omitempty"` // New status
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                     // Optional event description
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`                           // Location where event occurred
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`     // When the event occurred
	RecordedBy    string                 `protobuf:"bytes,7,opt,name=recorded_by,json=recordedBy,proto3" json:"recorded_by,omitempty"`     // Who recorded the event (user/system ID)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusEvent) Reset() {
	*x = StatusEvent{}
	mi := &file_shipment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEvent) ProtoMessage() {}

func (x *StatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEvent.ProtoReflect.Descriptor instead.
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{3}
}

func (x *StatusEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusEvent) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *StatusEvent) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_STATUS_UNSPECIFIED
}

func (x *StatusEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StatusEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *StatusEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *StatusEvent) GetRecordedBy() string {
	if x != nil {
		return x.RecordedBy
	}
	return ""
}

// CreateShipmentRequest - request to create a new shipment
type CreateShipmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber string                 `protobuf:"bytes,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Origin          string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination     string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Driver          *DriverDetails         `protobuf:"bytes,4,opt,name=driver,proto3" json:"driver,omitempty"`
	Unit            *UnitDetails           `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	ShipmentAmount  float64                `protobuf:"fixed64,6,opt,name=shipment_amount,json=shipmentAmount,proto3" json:"shipment_amount,omitempty"`
	DriverRevenue   float64                `protobuf:"fixed64,7,opt,name=driver_revenue,json=driverRevenue,proto3" json:"driver_revenue,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_shipment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{4}
}

func (x *CreateShipmentRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreateShipmentRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CreateShipmentRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateShipmentRequest) GetDriver() *DriverDetails {
	if x != nil {
		return x.Driver
	}
	return nil
}

func (x *CreateShipmentRequest) GetUnit() *UnitDetails {
	if x != nil {
		return x.Unit
	}
	return nil
}

func (x *CreateShipmentRequest) GetShipmentAmount() float64 {
	if x != nil {
		return x.ShipmentAmount
	}
	return 0
}

func (x *CreateShipmentRequest) GetDriverRevenue() float64 {
	if x != nil {
		return x.DriverRevenue
	}
	return 0
}

// CreateShipmentResponse - response after creating a shipment
type CreateShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentResponse) Reset() {
	*x = CreateShipmentResponse{}
	mi := &file_shipment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentResponse) ProtoMessage() {}

func (x *CreateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentResponse.ProtoReflect.Descriptor instead.
func (*CreateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{5}
}

func (x *CreateShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

func (x *CreateShipmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetShipmentRequest - request to get shipment by reference number
type GetShipmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber string                 `protobuf:"bytes,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetShipmentRequest) Reset() {
	*x = GetShipmentRequest{}
	mi := &file_shipment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentRequest) ProtoMessage() {}

func (x *GetShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{6}
}

func (x *GetShipmentRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

// GetShipmentResponse - response with shipment details
type GetShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentResponse) Reset() {
	*x = GetShipmentResponse{}
	mi := &file_shipment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentResponse) ProtoMessage() {}

func (x *GetShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{7}
}

func (x *GetShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

// AddStatusEventRequest - request to add a status change event
type AddStatusEventRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber string                 `protobuf:"bytes,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	NewStatus       ShipmentStatus         `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=shipment.ShipmentStatus" json:"new_status,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location        string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	RecordedBy      string                 `protobuf:"bytes,5,opt,name=recorded_by,json=recordedBy,proto3" json:"recorded_by,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddStatusEventRequest) Reset() {
	*x = AddStatusEventRequest{}
	mi := &file_shipment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStatusEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStatusEventRequest) ProtoMessage() {}

func (x *AddStatusEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStatusEventRequest.ProtoReflect.Descriptor instead.
func (*AddStatusEventRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{8}
}

func (x *AddStatusEventRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *AddStatusEventRequest) GetNewStatus() ShipmentStatus {
	if x != nil {
		return x.NewStatus
	}
	return ShipmentStatus_STATUS_UNSPECIFIED
}

func (x *AddStatusEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddStatusEventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AddStatusEventRequest) GetRecordedBy() string {
	if x != nil {
		return x.RecordedBy
	}
	return ""
}

// AddStatusEventResponse - response after adding status event
type AddStatusEventResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Event           *StatusEvent           `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	UpdatedShipment *Shipment              `protobuf:"bytes,2,opt,name=updated_shipment,json=updatedShipment,proto3" json:"updated_shipment,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddStatusEventResponse) Reset() {
	*x = AddStatusEventResponse{}
	mi := &file_shipment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStatusEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStatusEventResponse) ProtoMessage() {}

func (x *AddStatusEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStatusEventResponse.ProtoReflect.Descriptor instead.
func (*AddStatusEventResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{9}
}

func (x *AddStatusEventResponse) GetEvent() *StatusEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AddStatusEventResponse) GetUpdatedShipment() *Shipment {
	if x != nil {
		return x.UpdatedShipment
	}
	return nil
}

func (x *AddStatusEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetShipmentHistoryRequest - request to get all events for a shipment
type GetShipmentHistoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber string                 `protobuf:"bytes,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetShipmentHistoryRequest) Reset() {
	*x = GetShipmentHistoryRequest{}
	mi := &file_shipment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentHistoryRequest) ProtoMessage() {}

func (x *GetShipmentHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentHistoryRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{10}
}

func (x *GetShipmentHistoryRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

// GetShipmentHistoryResponse - response with list of status events
type GetShipmentHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*StatusEvent         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentHistoryResponse) Reset() {
	*x = GetShipmentHistoryResponse{}
	mi := &file_shipment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentHistoryResponse) ProtoMessage() {}

func (x *GetShipmentHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentHistoryResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{11}
}

func (x *GetShipmentHistoryResponse) GetEvents() []*StatusEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_shipment_proto protoreflect.FileDescriptor

const file_shipment_proto_rawDesc = "" +
	"\n" +
	"\x0eshipment.proto\x12\bshipment\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x03\n" +
	"\bShipment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10reference_number\x18\x02 \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x12?\n" +
	"\x0ecurrent_status\x18\x05 \x01(\x0e2\x18.shipment.ShipmentStatusR\rcurrentStatus\x12/\n" +
	"\x06driver\x18\x06 \x01(\v2\x17.shipment.DriverDetailsR\x06driver\x12)\n" +
	"\x04unit\x18\a \x01(\v2\x15.shipment.UnitDetailsR\x04unit\x12'\n" +
	"\x0fshipment_amount\x18\b \x01(\x01R\x0eshipmentAmount\x12%\n" +
	"\x0edriver_revenue\x18\t \x01(\x01R\rdriverRevenue\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"p\n" +
	"\rDriverDetails\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1f\n" +
	"\vdriver_name\x18\x02 \x01(\tR\n" +
	"driverName\x12!\n" +
	"\fdriver_phone\x18\x03 \x01(\tR\vdriverPhone\"f\n" +
	"\vUnitDetails\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\tR\x06unitId\x12\x1b\n" +
	"\tunit_type\x18\x02 \x01(\tR\bunitType\x12!\n" +
	"\fplate_number\x18\x03 \x01(\tR\vplateNumber\"\x8c\x02\n" +
	"\vStatusEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vshipment_id\x18\x02 \x01(\tR\n" +
	"shipmentId\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.shipment.ShipmentStatusR\x06status\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x1f\n" +
	"\vrecorded_by\x18\a \x01(\tR\n" +
	"recordedBy\"\xa8\x02\n" +
	"\x15CreateShipmentRequest\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12/\n" +
	"\x06driver\x18\x04 \x01(\v2\x17.shipment.DriverDetailsR\x06driver\x12)\n" +
	"\x04unit\x18\x05 \x01(\v2\x15.shipment.UnitDetailsR\x04unit\x12'\n" +
	"\x0fshipment_amount\x18\x06 \x01(\x01R\x0eshipmentAmount\x12%\n" +
	"\x0edriver_revenue\x18\a \x01(\x01R\rdriverRevenue\"b\n" +
	"\x16CreateShipmentResponse\x12.\n" +
	"\bshipment\x18\x01 \x01(\v2\x12.shipment.ShipmentR\bshipment\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\x12GetShipmentRequest\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\tR\x0freferenceNumber\"E\n" +
	"\x13GetShipmentResponse\x12.\n" +
	"\bshipment\x18\x01 \x01(\v2\x12.shipment.ShipmentR\bshipment\"\xda\x01\n" +
	"\x15AddStatusEventRequest\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\tR\x0freferenceNumber\x127\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x18.shipment.ShipmentStatusR\tnewStatus\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1f\n" +
	"\vrecorded_by\x18\x05 \x01(\tR\n" +
	"recordedBy\"\x9e\x01\n" +
	"\x16AddStatusEventResponse\x12+\n" +
	"\x05event\x18\x01 \x01(\v2\x15.shipment.StatusEventR\x05event\x12=\n" +
	"\x10updated_shipment\x18\x02 \x01(\v2\x12.shipment.ShipmentR\x0fupdatedShipment\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"F\n" +
	"\x19GetShipmentHistoryRequest\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\tR\x0freferenceNumber\"K\n" +
	"\x1aGetShipmentHistoryResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.shipment.StatusEventR\x06events*\xa8\x01\n" +
	"\x0eShipmentStatus\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x14\n" +
	"\x10STATUS_PICKED_UP\x10\x02\x12\x15\n" +
	"\x11STATUS_IN_TRANSIT\x10\x03\x12\x14\n" +
	"\x10STATUS_DELIVERED\x10\x04\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x05\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x062\xe8\x02\n" +
	"\x0fShipmentService\x12S\n" +
	"\x0eCreateShipment\x12\x1f.shipment.CreateShipmentRequest\x1a .shipment.CreateShipmentResponse\x12J\n" +
	"\vGetShipment\x12\x1c.shipment.GetShipmentRequest\x1a\x1d.shipment.GetShipmentResponse\x12S\n" +
	"\x0eAddStatusEvent\x12\x1f.shipment.AddStatusEventRequest\x1a .shipment.AddStatusEventResponse\x12_\n" +
	"\x12GetShipmentHistory\x12#.shipment.GetShipmentHistoryRequest\x1a$.shipment.GetShipmentHistoryResponseB Z\x1evektor-shipment/proto/shipmentb\x06proto3"

var (
	file_shipment_proto_rawDescOnce sync.Once
	file_shipment_proto_rawDescData []byte
)

func file_shipment_proto_rawDescGZIP() []byte {
	file_shipment_proto_rawDescOnce.Do(func() {
		file_shipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipment_proto_rawDesc), len(file_shipment_proto_rawDesc)))
	})
	return file_shipment_proto_rawDescData
}

var file_shipment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shipment_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_shipment_proto_goTypes = []any{
	(ShipmentStatus)(0),                // 0: shipment.ShipmentStatus
	(*Shipment)(nil),                   // 1: shipment.Shipment
	(*DriverDetails)(nil),              // 2: shipment.DriverDetails
	(*UnitDetails)(nil),                // 3: shipment.UnitDetails
	(*StatusEvent)(nil),                // 4: shipment.StatusEvent
	(*CreateShipmentRequest)(nil),      // 5: shipment.CreateShipmentRequest
	(*CreateShipmentResponse)(nil),     // 6: shipment.CreateShipmentResponse
	(*GetShipmentRequest)(nil),         // 7: shipment.GetShipmentRequest
	(*GetShipmentResponse)(nil),        // 8: shipment.GetShipmentResponse
	(*AddStatusEventRequest)(nil),      // 9: shipment.AddStatusEventRequest
	(*AddStatusEventResponse)(nil),     // 10: shipment.AddStatusEventResponse
	(*GetShipmentHistoryRequest)(nil),  // 11: shipment.GetShipmentHistoryRequest
	(*GetShipmentHistoryResponse)(nil), // 12: shipment.GetShipmentHistoryResponse
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
}
var file_shipment_proto_depIdxs = []int32{
	0,  // 0: shipment.Shipment.current_status:type_name -> shipment.ShipmentStatus
	2,  // 1: shipment.Shipment.driver:type_name -> shipment.DriverDetails
	3,  // 2: shipment.Shipment.unit:type_name -> shipment.UnitDetails
	13, // 3: shipment.Shipment.created_at:type_name -> google.protobuf.Timestamp
	13, // 4: shipment.Shipment.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: shipment.StatusEvent.status:type_name -> shipment.ShipmentStatus
	13, // 6: shipment.StatusEvent.occurred_at:type_name -> google.protobuf.Timestamp
	2,  // 7: shipment.CreateShipmentRequest.driver:type_name -> shipment.DriverDetails
	3,  // 8: shipment.CreateShipmentRequest.unit:type_name -> shipment.UnitDetails
	1,  // 9: shipment.CreateShipmentResponse.shipment:type_name -> shipment.Shipment
	1,  // 10: shipment.GetShipmentResponse.shipment:type_name -> shipment.Shipment
	0,  // 11: shipment.AddStatusEventRequest.new_status:type_name -> shipment.ShipmentStatus
	4,  // 12: shipment.AddStatusEventResponse.event:type_name -> shipment.StatusEvent
	1,  // 13: shipment.AddStatusEventResponse.updated_shipment:type_name -> shipment.Shipment
	4,  // 14: shipment.GetShipmentHistoryResponse.events:type_name -> shipment.StatusEvent
	5,  // 15: shipment.ShipmentService.CreateShipment:input_type -> shipment.CreateShipmentRequest
	7,  // 16: shipment.ShipmentService.GetShipment:input_type -> shipment.GetShipmentRequest
	9,  // 17: shipment.ShipmentService.AddStatusEvent:input_type -> shipment.AddStatusEventRequest
	11, // 18: shipment.ShipmentService.GetShipmentHistory:input_type -> shipment.GetShipmentHistoryRequest
	6,  // 19: shipment.ShipmentService.CreateShipment:output_type -> shipment.CreateShipmentResponse
	8,  // 20: shipment.ShipmentService.GetShipment:output_type -> shipment.GetShipmentResponse
	10, // 21: shipment.ShipmentService.AddStatusEvent:output_type -> shipment.AddStatusEventResponse
	12, // 22: shipment.ShipmentService.GetShipmentHistory:output_type -> shipment.GetShipmentHistoryResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_shipment_proto_init() }
func file_shipment_proto_init() {
	if File_shipment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipment_proto_rawDesc), len(file_shipment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipment_proto_goTypes,
		DependencyIndexes: file_shipment_proto_depIdxs,
		EnumInfos:         file_shipment_proto_enumTypes,
		MessageInfos:      file_shipment_proto_msgTypes,
	}.Build()
	File_shipment_proto = out.File
	file_shipment_proto_goTypes = nil
	file_shipment_proto_depIdxs = nil
}
