apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: "development"
  GATEWAY_HTTP_ADDR: ":8081"
  # Config for PostgreSQL
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "shipment_user"
  POSTGRES_PASSWORD: "shipment_pass"
  POSTGRES_DB_SHIPMENT: "shipment_db"
  # Config for RabbitMQ
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
